### ISSUE TITLE
Application Areas and Negotiation models.

### ISSUE THREAD

**Issue by nsankar** [yasserfarouk/negmas#15]
@yasserfarouk 

Sir, Thanks for developing this excellent library with good documentation.

I would like to know 
 (a) what are some of the other business areas where this negotiation agents paradigm can be used (I mean other than the typical factory or supply chain process ).  For instance, can this be used for financial portfolio optimization for example as a model, a seller offers to construct  financial portfolio for the buyer with a certain monetary return value and risk where as the buyer expects the seller to construct a low risk portfolio with a high return over a certain tenure. ?

(b) Can this approach be used to solve operations research problems like route planning or optimization?

(c) How does  Negmas' approach differ from typical constraint  based optimization methods?

Would be great if you can share your thoughts and inputs.  Thank you in advance.

**Comment by yasserfarouk** [comment]
Thank you for your interest in NegMAS

(a) There are several business applications for automated negotiation. Not sure about the specific application you mentioned but I know that automated negotiation has been used for collaborative optimization of unmanned vehicles for example.

(b) Yes it can. Automated negotiation can be thought of as a form of distributed optimization with privacy-preserving properties (as the negotiators do not share their ufuns). 

(c) I am not sure how to answer this one. For me, I do not see any similarity between NegMAS and constraint-based optimization methods. NegMAS is just a platform upon which we can develop automated negotiators embedded within simulations. It does not try explicitly to solve any optimization problem.

**Comment by nsankar** [comment]
@yasserfarouk thanks for the response.
