### ISSUE TITLE
monitor init

### ISSUE THREAD

**Issue by YueNing** [yasserfarouk/negmas#4]
https://github.com/yasserfarouk/negmas/blob/5e3fb608c46c9241d603a42d88f424dfaeb437f6/negmas/situated.py#L1249

call init function of monitor at the step 0, not step function
` monitor.step(self)  -> monitor.init(self)`

**Comment by yasserfarouk** [comment]
Actually both are called

**Comment by yasserfarouk** [comment]
The issue was already handled
